2012/06/07 23:50:25 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/login
---
2012/06/07 23:50:30 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/index.php
---
2012/06/07 23:50:33 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/07 23:50:36 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/07 23:51:12 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/07 23:51:13 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/07 23:51:15 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/08 00:06:48 [error] [exception.CException] exception 'CException' with message 'Alias "translate.components.Ei18n" is invalid. Make sure it points to an existing PHP file.' in /media/Dados/WebSites/twitter/framework/YiiBase.php:318
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/YiiBase.php(198): YiiBase::import('translate.compo...', true)
#1 /media/Dados/WebSites/twitter/framework/base/CModule.php(387): YiiBase::createComponent(Array)
#2 /media/Dados/WebSites/twitter/framework/base/CModule.php(493): CModule->getComponent('translate')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(146): CModule->preloadComponents()
#4 /media/Dados/WebSites/twitter/framework/YiiBase.php(127): CApplication->__construct('/media/Dados/We...')
#5 /media/Dados/WebSites/twitter/framework/YiiBase.php(100): YiiBase::createApplication('CWebApplication', '/media/Dados/We...')
#6 /media/Dados/WebSites/twitter/public_html/index.php(12): YiiBase::createWebApplication('/media/Dados/We...')
#7 {main}
REQUEST_URI=/twitter/public_html/
---
2012/06/08 02:24:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login".' in /media/Dados/WebSites/twitter/framework/web/CController.php:484
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(271): CController->missingAction('login')
#1 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('login')
#2 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/login
---
2012/06/19 23:54:51 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user
HTTP_REFERER=http://localhost/twitter/public_html/index.php?r=site/user
---
2012/06/19 23:54:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/1')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/1
---
2012/06/19 23:55:01 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/id=1')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/id=1
---
2012/06/20 00:42:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "inde".' in /media/Dados/WebSites/twitter/framework/web/CController.php:484
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(271): CController->missingAction('inde')
#1 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('inde')
#2 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/inde')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/inde
---
2012/06/20 00:43:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "inde".' in /media/Dados/WebSites/twitter/framework/web/CController.php:484
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(271): CController->missingAction('inde')
#1 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('inde')
#2 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/inde')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/inde
---
2012/06/20 00:55:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:87
Stack trace:
#0 [internal function]: SiteController->actionUser('1')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=1
---
2012/06/23 20:45:19 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user
---
2012/06/23 20:45:46 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user
---
2012/06/23 20:45:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'O sistema não foi capaz de encontrar a ação "user$id" solicitada.' in /media/Dados/WebSites/twitter/framework/web/CController.php:484
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(271): CController->missingAction('user$id')
#1 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user$id')
#2 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user$id')
#3 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#4 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#5 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user$id
---
2012/06/23 20:46:13 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/tonyb...')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/tonybolzan
---
2012/06/23 20:46:15 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Sua requisição é inválida.' in /media/Dados/WebSites/twitter/framework/web/CController.php:337
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/CController.php(310): CController->invalidActionParams(Object(CInlineAction))
#1 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#2 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#3 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#5 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#6 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user')
#12 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#13 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#14 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user
---
2012/06/23 20:46:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('1')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=1
---
2012/06/23 20:46:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/23 21:56:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/23 21:57:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/23 21:57:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/23 21:57:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/23 21:58:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:69
Stack trace:
#0 [internal function]: SiteController->actionUser('tonybolza')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=tonybolza
---
2012/06/24 00:03:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Erro ao adicionar Usuário.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:143
Stack trace:
#0 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(50): SiteController->actionLogin()
#1 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#2 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#3 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#5 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#8 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#10 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('login')
#12 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/login')
#13 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#14 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#15 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/login
HTTP_REFERER=http://localhost/twitter/public_html/index.php?r=site/login
---
2012/06/24 00:28:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:98
Stack trace:
#0 [internal function]: SiteController->actionUser('teste')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=teste
---
2012/06/24 01:23:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Usuário Não Encontrado.' in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php:99
Stack trace:
#0 [internal function]: SiteController->actionUser('teste')
#1 /media/Dados/WebSites/twitter/framework/web/actions/CAction.php(107): ReflectionMethod->invokeArgs(Object(SiteController), Array)
#2 /media/Dados/WebSites/twitter/framework/web/actions/CInlineAction.php(48): CAction->runWithParamsInternal(Object(SiteController), Object(ReflectionMethod), Array)
#3 /media/Dados/WebSites/twitter/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#4 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#5 /media/Dados/WebSites/twitter/framework/web/widgets/COutputCache.php(152): CFilterChain->run()
#6 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): COutputCache->filter(Object(CFilterChain))
#7 /media/Dados/WebSites/twitter/framework/web/filters/CFilter.php(41): CFilterChain->run()
#8 /media/Dados/WebSites/twitter/framework/web/CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 /media/Dados/WebSites/twitter/framework/web/filters/CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 /media/Dados/WebSites/twitter/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 /media/Dados/WebSites/twitter/framework/web/CController.php(292): CFilterChain->run()
#12 /media/Dados/WebSites/twitter/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(276): CController->run('user')
#14 /media/Dados/WebSites/twitter/framework/web/CWebApplication.php(135): CWebApplication->runController('site/user/')
#15 /media/Dados/WebSites/twitter/framework/base/CApplication.php(162): CWebApplication->processRequest()
#16 /media/Dados/WebSites/twitter/public_html/index.php(12): CApplication->run()
#17 {main}
REQUEST_URI=/twitter/public_html/index.php?r=site/user/&id=teste
---
2012/06/24 01:58:24 [warning] [application] Failed to set unsafe attribute "password" of "User".
in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php (180)
in /media/Dados/WebSites/twitter/public_html/index.php (12)
2012/06/24 01:58:34 [warning] [application] Failed to set unsafe attribute "password" of "User".
in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php (180)
in /media/Dados/WebSites/twitter/public_html/index.php (12)
2012/06/24 01:58:59 [warning] [application] Failed to set unsafe attribute "password" of "User".
in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php (180)
in /media/Dados/WebSites/twitter/public_html/index.php (12)
2012/06/24 01:59:08 [warning] [application] Failed to set unsafe attribute "password" of "User".
in /media/Dados/WebSites/twitter/public_html/protected/controllers/SiteController.php (180)
in /media/Dados/WebSites/twitter/public_html/index.php (12)
